# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Byggðalagnir"
email: 'byggdalagnir@gmail.com'
<<<<<<< HEAD
quote: "Lagaðar lagnir áður en þú kemur til byggða"
=======
>>>>>>> 07d7de157e455bfb85eef537d0e49d51409d04fc
description: "Ég sinni öllum almennum pípulagningum af einskærri fagmennnsku og vandvirkni"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://byggdalagnir.is" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: 'byggdalagnir'
facebook_username: 'byggdalagnir'

# Build settings
markdown: kramdown

exclude:
  - node_modules/
  - yarn.lock
  - postcss.config.js
  - tailwind.config.js
  - purgecss.config.js
  - package.json
