name: Jekyll site CI

on:
  push:
    branches: [ main, gh-pages ]
  pull_request:
    branches: [ main, gh-pages ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && NODE_ENV=production npm install && JEKYLL_ENV=production jekyll build --future"
